### ISSUE TITLE
crash 1.18.2

### ISSUE THREAD

**Issue by Aceplante2** [tr7zw/3d-Skin-Layers#127]
Caused by opening a chest in the end?

Error while resolving a skin texture.
java.lang.NullPointerException
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.cache.LocalCache.put(LocalCache.java:4194)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.cache.LocalCache$LocalManualCache.put(LocalCache.java:4880)
	at TRANSFORMER/skinlayers3d@1.5.2/dev.tr7zw.skinlayers.SkinUtil.getTexture(SkinUtil.java:70)
	at TRANSFORMER/skinlayers3d@1.5.2/dev.tr7zw.skinlayers.SkinUtil.setup3dLayers(SkinUtil.java:151)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.BlockEntityWithoutLevelRenderer.handler$elo000$renderByItem(BlockEntityWithoutLevelRenderer.java:1067)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.BlockEntityWithoutLevelRenderer.m_108829_(BlockEntityWithoutLevelRenderer.java)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:159)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.entity.ItemRenderer.m_115127_(ItemRenderer.java:258)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.entity.ItemRenderer.m_174235_(ItemRenderer.java:299)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.entity.ItemRenderer.m_174277_(ItemRenderer.java:290)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.entity.ItemRenderer.m_115218_(ItemRenderer.java:282)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.inventory.MerchantScreen.m_6305_(MerchantScreen.java:218)
	at TRANSFORMER/forge@40.2.9/net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:403)
	at TRANSFORMER/forge@40.2.9/net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:890)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.9/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

**Comment by tr7zw** [comment]
It looks like a Merchant screen contained a player head that couldn't be processed(some broken data on it). It might be "fixed"(ignored) by a future backport, as 1.18 is not a supported version anymore. Will take some time till I've created my new custom build-system.

**Comment by Aceplante2** [comment]
yea, if a head cannot be loaded for some reason, ignoring it would be a good solution. The odd thing was, I was opening a chest that did not have any heads in it. Still, fair enough if its not your top priority, but thank you

**Comment by tr7zw** [comment]
> at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.entity.ItemRenderer.m_115218_(ItemRenderer.java:282)
at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.inventory.MerchantScreen.m_6305_(MerchantScreen.java:218)
at TRANSFORMER/forge@40.2.9/net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:403)

The crash report states that it's a MerchantScreen, not a chest. So I'd assume something like the vanillatweaks wandering trader datapack?

**Comment by tr7zw** [comment]
Also please re-test with 1.6.0.

**Comment by Aceplante2** [comment]
I dont actually remember what was causing this bug, not sure how I would recreate the cause

**Comment by tr7zw** [comment]
I'll close it, as it *should* be fixed.
