### ISSUE TITLE
Instant crash on loading world in 1.21.1

### ISSUE THREAD

**Issue by dylanparry** [tr7zw/3d-Skin-Layers#191]
Hi,

I'm getting an instant crash to desktop when I open my world on 1.21.1. This is for a local world. I also got a similar crash on a server-hosted multiplayer world, but that didn't happen until I placed an item. Here's the log for the crash:

```
[15:05:45] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'boolean dev.tr7zw.skinlayers.SkinUtil.setup3dLayers(net.minecraft.class_742, dev.tr7zw.skinlayers.accessor.PlayerSettings, boolean, net.minecraft.class_591)'
	at knot/traben.entity_texture_features.compat.ETF3DSkinLayersUtil.renderHand(ETF3DSkinLayersUtil.java:44) ~[entity_texture_features_fabric_1.21-6.2.5.jar:?]
	at knot/net.minecraft.class_1007.etf$renderOnce(class_1007.java:1110) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1007.handler$zin000$entity_texture_features$etf$redirectNicely(class_1007.java:1076) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1007.method_23205(class_1007.java:195) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1007.method_4220(class_1007.java:181) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_759.method_3219(class_759.java:308) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_759.method_3228(class_759.java:482) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_759.method_22976(class_759.java:399) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3172(class_757.java:790) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3188(class_757.java:1114) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3192(class_757.java:850) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.8.jar:?]
```

This happened when using version 1.7.0, but doesn't happen when I downgrade back to 1.6.7. Any ideas?

**Comment by tr7zw** [comment]
Looks like ETF has some 3d skin layers hook that broke, so this will need an update of ETF. I might need to talk to them about what they need, so I can provide an API that doesn't break like this. @Traben-0

**Comment by dylanparry** [comment]
Thanks for the quick response. I just noticed the ETF line too :man_facepalming: I'll stick with 1.6.7 as you suggest and wait until ETF does an update to try it again :+1:

**Comment by Traben-0** [comment]
I should have a fix up early tomorrow

**Comment by tr7zw** [comment]
> I should have a fix up early tomorrow

As I said, best case we can define a clean api for what is needed for ETFs use-case, then I can change things without accidentally breaking it again in the future.

**Comment by Traben-0** [comment]
I'll give you a summary of what exactly I do tomorrow, 
iirc it is just a hook after the 3d layer rendering to render that part emissive, as well as a hook during render to modify the skin texture if etf needs to

**Comment by Traben-0** [comment]
Same for the first person hand rendering

**Comment by tr7zw** [comment]
Apparently there are also issues when animation resource packs like detailed animations get into the mix with the new render system where I inject the vanilla layer(at least on 1.20.1). I'm also available on your discord, so we can potentially talk there about how to fix and futureproof this stuff.

**Comment by Traben-0** [comment]
the ETF crash issue is now resolved

**Comment by dylanparry** [comment]
@Traben-0 awesome, thank you :tada:

**Comment by tr7zw** [comment]
Apparently there are also issues when animation resource packs like detailed animations get into the mix with the new render system where I inject the vanilla layer(at least on 1.20.1). I'm also available on your discord, so we can potentially talk there about how to fix and futureproof this stuff.
