### ISSUE TITLE
(Fabric 1.21.1) Game completely crashes when opening inventory.

### ISSUE THREAD

**Issue by 8BitBunnie** [tr7zw/3d-Skin-Layers#199]
I'm playing on Minecraft 1.21.1 with the following mods and the game completely crashes whenever the inventory is opened. Not enough crashes ("custom" updated to 1.21.1) cites Fabric Screen API and 3D Skin Layers, which is no longer installed, to be the issue. The crash log is included.
![image](https://github.com/user-attachments/assets/1346e610-64ab-4e2f-829c-bf61f7296bf6)

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-11-16 23:09:44
Description: Rendering entity in world

java.lang.IllegalStateException: Not building!
	at knot//net.minecraft.class_287.method_60802(class_287.java:76)
	at knot//net.minecraft.class_287.method_60805(class_287.java:95)
	at knot//net.minecraft.class_287.method_22912(class_287.java:156)
	at knot//dev.tr7zw.skinlayers.render.CustomizableModelPart.compile(CustomizableModelPart.java:195)
	at knot//dev.tr7zw.skinlayers.render.CustomizableModelPart.render(CustomizableModelPart.java:113)
	at knot//dev.tr7zw.skinlayers.renderlayers.CustomLayerFeatureRenderer.renderLayers(CustomLayerFeatureRenderer.java:114)
	at knot//dev.tr7zw.skinlayers.renderlayers.CustomLayerFeatureRenderer.render(CustomLayerFeatureRenderer.java:99)
	at knot//dev.tr7zw.skinlayers.renderlayers.CustomLayerFeatureRenderer.method_4199(CustomLayerFeatureRenderer.java:37)
	at knot//net.minecraft.class_922.method_4054(class_922.java:150)
	at knot//net.minecraft.class_1007.method_4215(class_1007.java:68)
	at knot//net.minecraft.class_1007.method_3936(class_1007.java:45)
	at knot//net.minecraft.class_898.method_3954(class_898.java:148)
	at knot//net.minecraft.class_490.method_29977(class_490.java:155)
	at knot//com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:720)
	at knot//net.minecraft.class_490.method_48472(class_490.java:155)
	at knot//net.minecraft.class_490.method_2486(class_490.java:130)
	at knot//net.minecraft.class_490.method_2389(class_490.java:99)
	at knot//net.minecraft.class_465.method_25420(class_465.java:172)
	at knot//net.minecraft.class_437.method_25394(class_437.java:126)
	at knot//net.minecraft.class_465.method_25394(class_465.java:100)
	at knot//net.minecraft.class_485.method_25394(class_485.java:32)
	at knot//net.minecraft.class_490.method_25394(class_490.java:81)
	at knot//net.minecraft.class_437.method_47413(class_437.java:117)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$251(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bic000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)
	at knot//net.minecraft.class_757.method_3192(class_757.java:913)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_287.method_60802(class_287.java:76)
	at knot//net.minecraft.class_287.method_60805(class_287.java:95)
	at knot//net.minecraft.class_287.method_22912(class_287.java:156)
	at knot//dev.tr7zw.skinlayers.render.CustomizableModelPart.compile(CustomizableModelPart.java:195)
	at knot//dev.tr7zw.skinlayers.render.CustomizableModelPart.render(CustomizableModelPart.java:113)
	at knot//dev.tr7zw.skinlayers.renderlayers.CustomLayerFeatureRenderer.renderLayers(CustomLayerFeatureRenderer.java:114)
	at knot//dev.tr7zw.skinlayers.renderlayers.CustomLayerFeatureRenderer.render(CustomLayerFeatureRenderer.java:99)
	at knot//dev.tr7zw.skinlayers.renderlayers.CustomLayerFeatureRenderer.method_4199(CustomLayerFeatureRenderer.java:37)
	at knot//net.minecraft.class_922.method_4054(class_922.java:150)
	at knot//net.minecraft.class_1007.method_4215(class_1007.java:68)
	at knot//net.minecraft.class_1007.method_3936(class_1007.java:45)
	at knot//net.minecraft.class_898.method_3954(class_898.java:148)
	at knot//net.minecraft.class_490.method_29977(class_490.java:155)
	at knot//com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:720)
	at knot//net.minecraft.class_490.method_48472(class_490.java:155)
	at knot//net.minecraft.class_490.method_2486(class_490.java:130)
	at knot//net.minecraft.class_490.method_2389(class_490.java:99)
	at knot//net.minecraft.class_465.method_25420(class_465.java:172)
	at knot//net.minecraft.class_437.method_25394(class_437.java:126)
	at knot//net.minecraft.class_465.method_25394(class_465.java:100)
	at knot//net.minecraft.class_485.method_25394(class_485.java:32)
	at knot//net.minecraft.class_490.method_25394(class_490.java:81)
	at knot//net.minecraft.class_437.method_47413(class_437.java:117)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$251(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bic000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 91
	Entity Name: 8BitBunnie
	Entity's Exact location: -1.50, 60.00, -3.65
	Entity's Block location: World: (-2,60,-4), Section: (at 14,12,12 in -1,3,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Air:300s,Brain:{memories:{}},DataVersion:3955,DeathTime:0s,EnderItems:[],FallDistance:0.0f,FallFlying:0b,Fire:-20s,Health:18.0f,HurtByTimestamp:0,HurtTime:0s,Inventory:[{Slot:0b,components:{"minecraft:damage":1296},count:1,id:"minecraft:diamond_pickaxe"},{Slot:1b,components:{"minecraft:damage":783},count:1,id:"minecraft:diamond_shovel"},{Slot:2b,components:{"minecraft:damage":296},count:1,id:"minecraft:diamond_axe"},{Slot:3b,components:{"minecraft:damage":272},count:1,id:"minecraft:diamond_hoe"},{Slot:4b,count:1,id:"minecraft:bucket"},{Slot:8b,count:1,id:"minecraft:shulker_shell"},{Slot:9b,count:28,id:"minecraft:torch"},{Slot:10b,components:{"minecraft:damage":85},count:1,id:"minecraft:iron_pickaxe"},{Slot:12b,count:1,id:"minecraft:white_wool"},{Slot:16b,count:4,id:"minecraft:egg"},{Slot:23b,count:1,id:"minecraft:amethyst_block"},{Slot:100b,components:{"minecraft:damage":21},count:1,id:"minecraft:diamond_boots"},{Slot:101b,components:{"minecraft:damage":21},count:1,id:"minecraft:diamond_leggings"},{Slot:102b,components:{"minecraft:damage":12},count:1,id:"minecraft:diamond_chestplate"},{Slot:103b,components:{"minecraft:damage":21},count:1,id:"minecraft:diamond_helmet"}],Invulnerable:0b,LastDeathLocation:{dimension:"minecraft:the_nether",pos:[I;-3,-229,-2]},Motion:[0.0d,-0.0784000015258789d,0.0d],OnGround:1b,PortalCooldown:0,Pos:[-1.4990537571488831d,60.0d,-3.6537423674664486d],Rotation:[235.03104f,-23.213379f],Score:-6422,SelectedItemSlot:6,SleepTimer:0s,UUID:[I;-1005328668,1389774449,-1431841003,-1027631184],XpLevel:41,XpP:0.2559284f,XpSeed:0,XpTotal:3176,abilities:{flySpeed:0.05f,flying:0b,instabuild:0b,invulnerable:0b,mayBuild:1b,mayfly:0b,walkSpeed:0.1f},attributes:[{base:0.0d,id:"minecraft:generic.armor_toughness"},{base:4.0d,id:"minecraft:generic.attack_speed"},{base:3.0d,id:"minecraft:player.entity_interaction_range"},{base:0.0d,id:"minecraft:generic.armor"},{base:4.5d,id:"minecraft:player.block_interaction_range"},{base:0.10000000149011612d,id:"minecraft:generic.movement_speed"}],current_impulse_context_reset_grace_time:0,foodExhaustionLevel:2.9815934f,foodLevel:14,foodSaturationLevel:0.0f,foodTickTimer:0,ignore_fall_damage_from_current_explosion:0b}
Stacktrace:
	at knot//net.minecraft.class_898.method_3954(class_898.java:148)
	at knot//net.minecraft.class_490.method_29977(class_490.java:155)
	at knot//com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:720)
	at knot//net.minecraft.class_490.method_48472(class_490.java:155)
	at knot//net.minecraft.class_490.method_2486(class_490.java:130)
	at knot//net.minecraft.class_490.method_2389(class_490.java:99)
	at knot//net.minecraft.class_465.method_25420(class_465.java:172)
	at knot//net.minecraft.class_437.method_25394(class_437.java:126)
	at knot//net.minecraft.class_465.method_25394(class_465.java:100)
	at knot//net.minecraft.class_485.method_25394(class_485.java:32)
	at knot//net.minecraft.class_490.method_25394(class_490.java:81)
	at knot//net.minecraft.class_437.method_47413(class_437.java:117)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$251(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bic000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)
	at knot//net.minecraft.class_757.method_3192(class_757.java:913)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@18dcaaf5
	Location: 0.00,0.00,0.00 - World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at knot//net.minecraft.class_898.method_3954(class_898.java:148)
	at knot//net.minecraft.class_490.method_29977(class_490.java:155)
	at knot//com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:720)
	at knot//net.minecraft.class_490.method_48472(class_490.java:155)
	at knot//net.minecraft.class_490.method_2486(class_490.java:130)
	at knot//net.minecraft.class_490.method_2389(class_490.java:99)
	at knot//net.minecraft.class_465.method_25420(class_465.java:172)
	at knot//net.minecraft.class_437.method_25394(class_437.java:126)
	at knot//net.minecraft.class_465.method_25394(class_465.java:100)
	at knot//net.minecraft.class_485.method_25394(class_485.java:32)
	at knot//net.minecraft.class_490.method_25394(class_490.java:81)
	at knot//net.minecraft.class_437.method_47413(class_437.java:117)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$251(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bic000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)
	at knot//net.minecraft.class_757.method_3192(class_757.java:913)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (240, 132). Absolute: (960.000000, 528.000000)
	Screen size: Scaled: (480, 265). Absolute: (1920, 1057). Scale factor of 4.000000
Stacktrace:
	at knot//net.minecraft.class_757.method_3192(class_757.java:913)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 438517928 bytes (418 MiB) / 1539309568 bytes (1468 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700F
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.11
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 46892.82
	Virtual memory used (MiB): 41457.15
	Swap memory total (MiB): 30674.59
	Swap memory used (MiB): 3738.33
	Space in storage for jna.tmpdir (MiB): available: 226393.13, total: 953151.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 226393.13, total: 953151.00
	Space in storage for io.netty.native.workdir (MiB): available: 226393.13, total: 953151.00
	Space in storage for java.io.tmpdir (MiB): available: 226393.13, total: 953151.00
	Space in storage for workdir (MiB): available: 226393.13, total: 953151.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m
	Fabric Mods: 
		ambientsounds: AmbientSounds 6.1.3
		appleskin: AppleSkin 3.0.6+mc1.21
		architectury: Architectury 13.0.8
		autoswitch: AutoSwitch 9.1.2
			autoswitch-api: AutoSwitch API 3.0.0
		badoptimizations: BadOptimizations 2.2.0
		betteradvancements: Better Advancements 0.4.3.21
		betterf3: BetterF3 11.0.3
		betterthirdperson: Better Third Person 1.9.0
		chat_heads: Chat Heads 0.13.6
		chatimpressiveanimation: Chat Impressive Animation 1.2.0+mc1.21.1
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		creativecore: CreativeCore 2.12.22
			net_neoforged_bus: bus 7.2.0
		daycountmod: Day Count 1.3.0_1.21
		durabilitytooltip: Durability Tooltip 1.1.5
		elementa: Elementa 670
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.7
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.1
		essential: Essential 1.3.5.3
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		euphoria_patcher: Euphoria Patcher 1.4.3-r5.3-fabric
			io_sigpipe_jbsdiff: jbsdiff 1.0
		fabric-api: Fabric API 0.108.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.3.0+8e331c5719
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.23+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fallingtree: FallingTree 1.21.1.2
		ferritecore: FerriteCore 7.0.2-hotfix
		foodeffecttooltips: Food Effect Tooltips 1.1.1-1.21
		freecam: Freecam 1.3.0+mc1.21
		iris: Iris 1.8.0-beta.8+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		jamlib: JamLib 1.2.2+1.21.1
			blue_endless_jankson: jankson 1.2.3
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.8.4.113
		libipn: libIPN 6.1.1
		lithium: Lithium 0.14.2-snapshot+mc1.21.1-build.90
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.3
		mousetweaks: Mouse Tweaks 2.26
		nerb: Not Enough Recipe Book 0.4.1
		notenoughcrashes: Not Enough Crashes 4.4.8+1.21
		octolib: OctoLib 0.4.2
			org_yaml_snakeyaml: snakeyaml 2.2
		org_jetbrains_annotations: annotations 23.0.0
		placeholder-api: Placeholder API 2.4.1+1.21
		puzzle: Puzzle 2.0.1
			midnightlib: MidnightLib 1.6.3
		rightclickharvest: Right Click Harvest 4.4.3+1.21.1
		shulkerboxtooltip: Shulker Box Tooltip 5.1.2+1.21.1
		skinlayers3d: 3d-Skin-Layers 1.7.2
		sodium: Sodium 0.6.0+mc1.21.1
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		spark: spark 1.10.109
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		universalcraft: UniversalCraft 365
		vigilance: Vigilance 306
		voicechat: Simple Voice Chat 1.21.1-2.5.26
	Loaded Shaderpack: ComplementaryReimagined_r5.3 + EuphoriaPatches_1.4.3
		Profile: Custom (+55 options changed by user)
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), 3d-Skin-Layers (skinlayers3d), Fabric Screen API (v1) (fabric-screen-api-v1)

**Comment by sacizo** [comment]
I'm having the same issues it's ETF and 3D Skin Layers but only on versions 1.21 and 1.21.1

**Comment by tr7zw** [comment]
Update EMF/ETF.
