### ISSUE TITLE
CRASH 1.21.4

### ISSUE THREAD

**Issue by Shorkbee** [tr7zw/3d-Skin-Layers#205]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-12-07 14:07:28
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_9296.method_57511()" because "livingEntityRenderState.field_55316" is null
	at knot//net.minecraft.class_976.handler$dkh000$skinlayers3d$render(class_976.java:1055)
	at knot//net.minecraft.class_976.method_17159(class_976.java)
	at knot//net.minecraft.class_976.method_4199(class_976.java:20)
	at knot//net.minecraft.class_922.method_4054(class_922.java:115)
	at knot//net.minecraft.class_922.method_3936(class_922.java:40)
	at knot//net.minecraft.class_898.method_3954(class_898.java:162)
	at knot//net.minecraft.class_898.method_62424(class_898.java:149)
	at knot//net.minecraft.class_761.method_22977(class_761.java:987)
	at knot//net.minecraft.class_761.method_62207(class_761.java:864)
	at knot//net.minecraft.class_761.method_62214(class_761.java:642)
	at knot//net.minecraft.class_9909.method_61910(class_9909.java:67)
	at knot//net.minecraft.class_761.method_22710(class_761.java:552)
	at knot//net.minecraft.class_757.method_3188(class_757.java:733)
	at knot//net.minecraft.class_757.method_3192(class_757.java:493)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1341)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_976.handler$dkh000$skinlayers3d$render(class_976.java:1055)
	at knot//net.minecraft.class_976.method_17159(class_976.java)
	at knot//net.minecraft.class_976.method_4199(class_976.java:20)
	at knot//net.minecraft.class_922.method_4054(class_922.java:115)
	at knot//net.minecraft.class_922.method_3936(class_922.java:40)
	at knot//net.minecraft.class_898.method_3954(class_898.java:162)
	at knot//net.minecraft.class_898.method_62424(class_898.java:149)
	at knot//net.minecraft.class_761.method_22977(class_761.java:987)
	at knot//net.minecraft.class_761.method_62207(class_761.java:864)
	at knot//net.minecraft.class_761.method_62214(class_761.java:642)
	at knot//net.minecraft.class_9909.method_61910(class_9909.java:67)
	at knot//net.minecraft.class_761.method_22710(class_761.java:552)
	at knot//net.minecraft.class_757.method_3188(class_757.java:733)

-- Entity being rendered --
Details:
	Entity Type: minecraft:pillager (net.minecraft.class_1604)
	Entity ID: 61
	Entity Name: Pillager
	Entity's Exact location: -1089.53, 84.00, -423.47
	Entity's Block location: World: (-1090,84,-424), Section: (at 14,4,8 in -69,5,-27; chunk contains blocks -1104,-64,-432 to -1089,319,-417), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,-64,-512 to -1025,319,-1)
	Entity's Momentum: 0.04, -0.08, 0.03
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at knot//net.minecraft.class_898.method_3954(class_898.java:162)
	at knot//net.minecraft.class_898.method_62424(class_898.java:149)
	at knot//net.minecraft.class_761.method_22977(class_761.java:987)
	at knot//net.minecraft.class_761.method_62207(class_761.java:864)
	at knot//net.minecraft.class_761.method_62214(class_761.java:642)
	at knot//net.minecraft.class_9909.method_61910(class_9909.java:67)
	at knot//net.minecraft.class_761.method_22710(class_761.java:552)
	at knot//net.minecraft.class_757.method_3188(class_757.java:733)
	at knot//net.minecraft.class_757.method_3192(class_757.java:493)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1341)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by tr7zw** [comment]
Duplicate #203

**Comment by tr7zw** [comment]
(Or actually, maybe not? Will have to compare the locations of the 2 reports)

**Comment by tr7zw** [comment]
Yep, this happens when wearing player heads without a profile(so the default steve).
