### ISSUE TITLE
Mod does not support MC 1.18.1

### ISSUE THREAD

**Issue by Andre601** [tr7zw/3d-Skin-Layers#28]
When trying to start Fabric with MC 1.18.1 while using 3DSkinLayers 1.3.1 do I receive the following error:
```
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod '3d Skin Layers' (skinlayers) 1.3.1 (C:\Users\Andreas\AppData\Roaming\gdlauncher_next\instances\Fabric 1.18.1\mods\3dSkinLayers-Fabric-1.3.1.jar) with any version that is compatible with:
		 - minecraft 1.18.1
Unmet dependency listing:
	 - Mod '3d Skin Layers' (skinlayers) 1.3.1 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
		 - 'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - mod '3d Skin Layers' (skinlayers) 1.3.1, reason: to replace
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: unknown
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446388, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b88, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+cbda931888, reason: newer version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod '3d Skin Layers' (skinlayers) 1.3.1 (C:\Users\Andreas\AppData\Roaming\gdlauncher_next\instances\Fabric 1.18.1\mods\3dSkinLayers-Fabric-1.3.1.jar) with any version that is compatible with:
		 - minecraft 1.18.1
Unmet dependency listing:
	 - Mod '3d Skin Layers' (skinlayers) 1.3.1 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
		 - 'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - mod '3d Skin Layers' (skinlayers) 1.3.1, reason: to replace
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: unknown
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446388, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b88, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+cbda931888, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

```

**Comment by Andre601** [comment]
Redownloading the mod fixed the issue. I suppose the CurseForge page just gave me the 1.17.1 version for whatever reason...

It would help if the jar files actually had their supported MC version(s) displayed in the name and not just the mod version itself...

**Comment by tr7zw** [comment]
> It would help if the jar files actually had their supported MC version(s) displayed in the name and not just the mod version itself...
That doesn't fully work, because then the file would say 1.18 (for some other mods of mine it says 1.18-pre1), and still work on 1.18.1. The correct indicator is on the file page:
![grafik](https://user-images.githubusercontent.com/5133936/146645772-de9de3bb-3b8d-4afc-8d11-2e4a607dc85d.png)

I only added the 1.18.1 tag last night, so might be that launchers don't yet have that info.
