### ISSUE TITLE
not working with Liteloader: 3dskinlayers.mixins.json:PlayerMixin: Unsupported mixin class version 52. Mixin requires compatibility level JAVA_8 or above

### ISSUE THREAD

**Issue by HowardZHY** [tr7zw/3d-Skin-Layers#39]
not working with LiteLoader
[16:27:43] [main/ERROR] [mixin/]: 3dskinlayers.mixins.json:PlayerMixin: Unsupported mixin class version 52. Mixin requires compatibility level JAVA_8 or above.
org.spongepowered.asm.mixin.transformer.InvalidMixinException: Unsupported mixin class version 52. Mixin requires compatibility level JAVA_8 or above.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validateClassVersion(MixinInfo.java:470) ~[liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validateMixin(MixinInfo.java:444) ~[liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:289) ~[liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:338) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.initConfigs(MixinTransformer.java:580) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.init(MixinTransformer.java:489) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:393) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:109) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_311]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_311]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_311]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_311]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[16:27:43] [main/ERROR] [mixin/]: 3dskinlayers.mixins.json:PlayerModelMixin: Unsupported mixin class version 52. Mixin requires compatibility level JAVA_8 or above.
org.spongepowered.asm.mixin.transformer.InvalidMixinException: Unsupported mixin class version 52. Mixin requires compatibility level JAVA_8 or above.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validateClassVersion(MixinInfo.java:470) ~[liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validateMixin(MixinInfo.java:444) ~[liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:289) ~[liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:338) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.initConfigs(MixinTransformer.java:580) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.init(MixinTransformer.java:489) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:393) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:109) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_311]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_311]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_311]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_311]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[16:27:43] [main/ERROR] [mixin/]: 3dskinlayers.mixins.json:PlayerRendererMixin: Unsupported mixin class version 52. Mixin requires compatibility level JAVA_8 or above.
org.spongepowered.asm.mixin.transformer.InvalidMixinException: Unsupported mixin class version 52. Mixin requires compatibility level JAVA_8 or above.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validateClassVersion(MixinInfo.java:470) ~[liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validateMixin(MixinInfo.java:444) ~[liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:289) ~[liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:338) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.initConfigs(MixinTransformer.java:580) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.init(MixinTransformer.java:489) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:393) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:109) [liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_311]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_311]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_311]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_311]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by tr7zw** [comment]
Ehhh liteloader is still a thing? Not sure what its issue is, because the compatibility level is set to JAVA_8. https://github.com/tr7zw/3d-Skin-Layers/blob/1.8/3dSkinLayers-Forge/src/main/resources/3dskinlayers.mixins.json#L5 Only tested it with 1.8.9 Forge.

**Comment by HowardZHY** [comment]
I always use JDK8U311



At 2022-03-14 18:02:23, "tr7zw" ***@***.***> wrote:

Ehhh liteloader is still a thing? Not sure what its issue is, because the compatibility level is set to JAVA_8. https://github.com/tr7zw/3d-Skin-Layers/blob/1.8/3dSkinLayers-Forge/src/main/resources/3dskinlayers.mixins.json#L5 Only tested it with 1.8.9 Forge.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tr7zw** [comment]
This is not an issue of the used jdk, this is lightloader scewing up the mixin loading by not loading the config correctly apparently. Also is liteloader even maintained at all, and since when is it able to load Forge mods?

**Comment by HowardZHY** [comment]
I think the liteloader-intergrated mixin is outdated



At 2022-03-14 20:55:29, "tr7zw" ***@***.***> wrote:

This is not an issue of the used jdk, this is lightloader scewing up the mixin loading by not loading the config correctly apparently. Also is liteloader even maintained at all, and since when is it able to load Forge mods?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tr7zw** [comment]
I'll close this issue. This is a (1.8)Forge mod, not a Liteloader mod, would be more luck than anything if it worked with liteloader.

**Comment by HowardZHY** [comment]
https://www.planetminecraft.com/forums/help/javaedition/1-8-9-and-1-12-2-how-to-use-fix-mods-with-mixin-and-liteloader-652704/
PS: 1.8 is differ from 1.8.9

**Comment by HowardZHY** [comment]
I replaced the outdated spongepowerd mixin in liteloader.jar with the mixin in 3dskinlayers.jar and it (and viaforge) works !!!



At 2022-03-14 21:13:38, "tr7zw" ***@***.***> wrote:

I'll close this issue. This is a (1.8)Forge mod, not a Liteloader mod, would be more luck than anything if it worked with liteloader.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
