### ISSUE TITLE
incompatibility

### ISSUE THREAD

**Issue by Fefedu973** [tr7zw/3d-Skin-Layers#66]
this mod is not compatible with fancy menu
java.lang.ClassCastException: class de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem$MenuPlayerEntity cannot be cast to class net.minecraft.class_742 (de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem$MenuPlayerEntity and net.minecraft.class_742 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @2473b9ce)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_591.handler$coo000$setupAnimEnd(class_591.java:540)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_591.method_17087(class_591.java:179)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_591.method_2819(class_591.java:22)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_922.method_4054(class_922.java:129)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem$MenuPlayerRenderer.render(PlayerEntityCustomizationItem.java:453)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.renderEntityStatic(PlayerEntityCustomizationItem.java:317)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.lambda$renderPlayerEntity$0(PlayerEntityCustomizationItem.java:292)
[17:47:35] [Render thread/INFO]: [STDERR]:     at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1171)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.renderPlayerEntity(PlayerEntityCustomizationItem.java:291)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.render(PlayerEntityCustomizationItem.java:236)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.menuhandler.MenuHandlerBase.onRenderPost(MenuHandlerBase.java:1246)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.fancymenu.menu.fancy.menuhandler.custom.MainMenuHandler.onRenderPost(MainMenuHandler.java:117)
[17:47:35] [Render thread/INFO]: [STDERR]:     at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
[17:47:35] [Render thread/INFO]: [STDERR]:     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:47:35] [Render thread/INFO]: [STDERR]:     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.konkrete.events.EventHandler.invokeEvent(EventHandler.java:115)
[17:47:35] [Render thread/INFO]: [STDERR]:     at de.keksuccino.konkrete.events.EventHandler.callEventsFor(EventHandler.java:102)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_757.handler$ccm000$beforeRenderScreen(class_757.java:6047)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_757.method_3192(class_757.java:877)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_310.method_1523(class_310.java:1122)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.class_310.method_1514(class_310.java:737)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.minecraft.client.main.Main.main(Main.java:236)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[17:47:35] [Render thread/INFO]: [STDERR]:     at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by tr7zw** [comment]
Hm there is no mention of anything 3d skin layers related in the crash log, and it seems to work fine for me? 
![grafik](https://user-images.githubusercontent.com/5133936/171923264-6f80a06b-1087-46ff-a314-5cb09cd70b07.png)

**Comment by tr7zw** [comment]
I can see the error in the log, but it also happens without 3d Skin Layers installed. So it's some other mod.
Edit: After some testing it seems to be incompatible with not enough animations because it's rendering a Player that is not a real player. But since it doesn't cause a crash this is probably a bit lower priority.
