### ISSUE TITLE
Error while loading the animated skin.

### ISSUE THREAD

**Issue by Pdam67** [tr7zw/3d-Skin-Layers#96]
Whenever I joined a server the skins for the players would load really slow and when they did it would show an error code

[Worker-Main-4/ERROR]: 
Error while loading the animated skin.
java.io.IOException: Server returned HTTP response code: 522 for URL: https://skins.trsha.re/94a14173-2991-4bed-9552-82ce9430343f.gif 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997) ~[?:?] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?] 	at dev.tr7zw.skinlayers.donor.DonorSkinProvider$1.run(DonorSkinProvider.java:100) ~[3dskinlayers-fabric-1.5.2-mc1.19.3.jar:?] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

It seems the animated skins you added are messing up the skin loading in someway on multiplayer servers (at least in the uk)
I was able to get this glitch working on multimc on a seperate instance with 3D Skin Layers and Entity culling installed

Please fix this if possible or make it possible to disable the doner skins

**Comment by Pdam67** [comment]
i'll check it out

**Comment by Pdam67** [comment]
This worked thanks!
